# Site settings
title: Sasha Plichta
email: sasha@plichta.org
url: sashaplichta.github.io
description: "Sasha Plichta's personal website and portfolio"
keywords: "portfolio, chemical engineering, artificial intelligence"
skills: "Chemical and Biological Engineer - AI/ML Enthusiast"
meta_author: Plichta Sasha

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Sasha Plichta
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sashaplichta/
  - title: github
    url: https://github.com/sashaplichta

# Postal address (add as many lines as necessary)
address:
  - line: San Francisco, CA

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

# #for posts
# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       permalink: ""

# Define collections
collections:
  posts:
    output: true
  models:
    output: true

# Set default values for collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
  - scope:
      path: ""
      type: "models"
    values:
      permalink: ""
